
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: TeamDev_development

test:
  <<: *default
  database: TeamDev_test

production:
  <<: *default
  database: TeamDev_production
  username: TeamDev
  password: <%= ENV['TEAMDEV_DATABASE_PASSWORD'] %>
